name: Generate Snake Animation

on:
  schedule:
    # Atualiza a cobra diariamente
    - cron: "0 0 * * *" 

  workflow_dispatch: # Permite que você execute manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: guhxs1010 # Coloque o seu nome de usuário do GitHub aqui
          svg_out_path: dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

